### ISSUE TITLE
Expose Spacy Morphological Annotation

### ISSUE THREAD

**Issue by GeorgeS2019** [curiosity-ai/catalyst#105]
https://universaldependencies.org/format.html#morphological-annotation

```
Case=Nom|Definite=Ind|Gender=Neut|Number=Plur


"dortiger Verfügung" dortiger Case=Dat|Degree=Pos|Gender=Fem|Number=Sing Verfügung Case=Dat|Gender=Fem|Number=Sing

```

https://github.com/stanfordnlp/CoreNLP/issues/1392

**Comment by joprice** [comment]
I see this was closed, but I don't see an obvious field on the IToken type that returns this data. I find this is the main difference between spacy and this library. Is there anyway it could be included in the token annotation?
