### ISSUE TITLE
The type or namespace name 'English' does not exist in the namespace 'Catalyst.Models' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by mrTR24** [curiosity-ai/catalyst#108]
![image](https://github.com/curiosity-ai/catalyst/assets/22214056/c654532d-23b8-4d7a-b558-2eb897c1aa6c)

**Comment by 53nch4** [comment]
Have you installed the English language pack via NuGet?

**Comment by mrTR24** [comment]
i did not know i had to install the Catalyst.Models.English nuget.
Working fine now.
Thanks 53ch4
