### ISSUE TITLE
Bug / Broken Build - StarSpace and FastText.cs ref Argument Errors

### ISSUE THREAD

**Issue by dgerding** [curiosity-ai/catalyst#20]
Hi,
Excited to try this project but when I pull the solution and build I get build errors in StarSpace.cs and FastText.cs.

Tried to sort output below.

Dave G

1>src\Models\Embeddings\StarSpace\StarSpace.cs(603,38,603,48): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(603,54,603,67): error CS1615: Argument 2 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(611,35,611,45): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(611,47,611,63): error CS1503: Argument 2: cannot convert from 'float' to 'float[]'
1>src\Models\Embeddings\StarSpace\StarSpace.cs(615,41,615,51): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(615,57,615,70): error CS1615: Argument 2 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(849,55,849,67): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(849,73,849,86): error CS1615: Argument 2 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(856,59,856,71): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(856,77,856,90): error CS1615: Argument 2 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(901,35,901,49): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(901,51,901,71): error CS1503: Argument 2: cannot convert from 'float' to 'float[]'

1>src\Models\Embeddings\StarSpace\StarSpace.cs(906,45,906,59): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(906,65,906,80): error CS1615: Argument 2 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(928,80,928,83): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(928,89,928,92): error CS1615: Argument 2 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(928,122,928,125): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\StarSpace\StarSpace.cs(928,131,928,134): error CS1615: Argument 2 may not be passed with the 'ref' keyword

FAST TEXT 
1>src\Models\Embeddings\FastText\FastText.cs(935,35,935,49): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\FastText\FastText.cs(935,51,935,70): error CS1503: Argument 2: cannot convert from 'float' to 'float[]'
1>src\Models\Embeddings\FastText\FastText.cs(955,31,955,45): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\FastText\FastText.cs(955,47,955,66): error CS1503: Argument 2: cannot convert from 'float' to 'float[]'
1>src\Models\Embeddings\FastText\FastText.cs(978,31,978,45): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\FastText\FastText.cs(978,47,978,72): error CS1503: Argument 2: cannot convert from 'float' to 'float[]'

1>src\Models\Embeddings\FastText\FastText.cs(1195,38,1195,44): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\FastText\FastText.cs(1203,31,1203,37): error CS1615: Argument 1 may not be passed with the 'ref' keyword
1>src\Models\Embeddings\FastText\FastText.cs(1203,39,1203,40): error CS1503: Argument 2: cannot convert from 'float' to 'float[]'

WARNINGS...
1>src\Models\Special\HyphenatedWordsCapturer.cs(19,40,19,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>src\Models\Normalizer\UpperCaseNormalizer.cs(19,40,19,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>src\Models\Normalizer\RemovePunctuationNormalizer.cs(20,40,20,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>src\Models\Normalizer\NumberToWordNormalizer.cs(20,40,20,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>src\Models\Normalizer\LowerCaseNormalizer.cs(19,40,19,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>src\Base\CharSpanExtensions.cs(188,47,188,49): warning CS0168: The variable 'ex' is declared but never used
1>src\Models\Normalizer\FoldToAsciiNormalizer.cs(23,40,23,51): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>src\Models\Embeddings\StarSpace\StarSpace.cs(223,17,223,27): warning CS0219: The variable 'impatience' is assigned but its value is never used
1>src\Models\Embeddings\StarSpace\StarSpace.cs(224,19,224,33): warning CS0219: The variable 'best_valid_err' is assigned but its value is never used

**Comment by rafael-aero** [comment]
Hi @dgerding!

Sorry, was in the middle of doing some changes to bring back netstandard2.0 support, must have pushed a broken commit in between. Can you try now again and let me know if it compiles fine?

FYI, there is also a nuget package available for it here: http://nuget.org/packages/Catalyst

**Comment by dgerding** [comment]
Trying now.

**Comment by dgerding** [comment]
All set. thanks!
