### ISSUE TITLE
Is Sentiment Analysis supported?

### ISSUE THREAD

**Issue by KSemenenko** [curiosity-ai/catalyst#30]
Is Sentiment Analysis supported? 
Maybe there are some examples?

**Comment by theolivenbaum** [comment]
Hi @KSemenenko,

We've no specific examples on sentiment analysis, but you could use the FastText classifier model for it (see [the text classification sample code](https://github.com/curiosity-ai/catalyst/blob/master/samples/TextClassification/Program.cs)). 

There are a few examples online on how to use FastText for sentiment analysis, such as https://towardsdatascience.com/twitter-sentiment-analysis-using-fasttext-9ccd04465597. 

The main idea is to feed your training data in with three possible labels (such as 'POSITIVE', 'NEGATIVE' or 'NEUTRAL'), and let the model learn from it.
