### ISSUE TITLE
Adding Catalyst to a UWP app causes OutOfMemoryException compiling.

### ISSUE THREAD

**Issue by JimGaleForce** [curiosity-ai/catalyst#31]
Just adding Catalyst to a UWP app (tried versions 17763, 18362) causes the error "Framework resource extraction failed. Exception of type 'System.OutOfMemoryException' was thrown." when **compiling**.

**To Reproduce**
Create a UWP app in Visual Studio 2019, add Catalyst through NuGet. Add the using, and possibly a use of it. Build for either x64 or x86.

**Expected behavior**
Compilation works.

**Comment by theolivenbaum** [comment]
From a quick search on google, could be related to this issue on the ML.Net repository: https://github.com/dotnet/machinelearning/issues/4366
