### ISSUE TITLE
Is it possible to implement a skills extractor with catalyst using Named Entity Recognition?

### ISSUE THREAD

**Issue by atresnjo** [curiosity-ai/catalyst#33]
**Is your feature request related to a problem? Please describe.**
Basically I am looking to build a service that can extract skills from a job ad.

**Describe the solution you'd like**
A sample text would be: "We are looking for backend developers who are proficient in C#"
and I'd like to extract "backend" and "C#" from it.

**Describe alternatives you've considered**
I got parts of it working with spaCy in python, but I'd like a .NET implementation.

**Comment by ThienTran8** [comment]
Waitting for a tutorial of custom NER with Catalyst

**Comment by theolivenbaum** [comment]
Hi @atresnjo & @ThienTran8 

We've support for 3 different types of models for NER:

- Gazetteer-like (i.e. [Spotter](https://github.com/curiosity-ai/catalyst/blob/master/Catalyst/src/Models/EntityRecognition/Spotter.cs)) 
- Regex-like (i.e. [PatternSpotter](https://github.com/curiosity-ai/catalyst/blob/master/Catalyst/src/Models/EntityRecognition/PatternSpotter.cs))
- Perceptron-based (i.e. [AveragePerceptronEntityRecognizer](https://github.com/curiosity-ai/catalyst/blob/master/Catalyst/src/Models/EntityRecognition/AveragePerceptronEntityRecognizer.cs))

There is a sample for the PatternSpotter here: https://github.com/curiosity-ai/catalyst/blob/master/samples/EntityRecognition/Program.cs

For the Spotter model, the usage is fairly similar, and you can train it from your own list of entities as this:

```` csharp

var spotter = new Spotter(Language.Any, 0, "programming", "ProgrammingLanguage");
spotter.Data.IgnoreCase = true; //In some cases, it might be better to set it to false, and only add upper/lower-case exceptions as required
spotter.Data.IgnoreOnlyNumeric = false;

spotter.AddEntry("C#");
spotter.AddEntry("Python");
spotter.AddEntry("C++");
spotter.AddEntry("Rust");
spotter.AddEntry("Java");

var nlp = Pipeline.TokenizerFor(Language.English);
nlp.Add(spotter);

var doc = new Document("", Language.English);

nlp.Process(doc);

````

**Comment by theolivenbaum** [comment]
I've updated the sample to include the Spotter training example: https://github.com/curiosity-ai/catalyst/blob/master/samples/EntityRecognition/Program.cs

**Comment by ThienTran8** [comment]
@theolivenbaum  Thank you for the update. It is great.

The part of Neuralizer with Add and Forget is quite useful. 

For my use case of Entity Recognition, I have two types of entities: **Material**(leather, brick,..) and **Object** (house, brick,..)

For example: Make a **brick** (Object) and make a **brick** (Material) house.

From your point of view, which technique will help to solve this confusion?

Thank you very much
