### ISSUE TITLE
In Language enum Luxembourgish is both 83 and 86

### ISSUE THREAD

**Issue by matteofabbri** [curiosity-ai/catalyst#34]
**Language**
Luxembourgish

**Describe the bug**
In Language enum Luxembourgish is both 83 and 86

83:    Limburgan_Limburger_Limburgish,
86:   Luxembourgish_Letzeburgesch,

**Comment by theolivenbaum** [comment]
Hi @matteofabbri - I'll try to move soon the remaining code that is outside of Catalyst (on https://www.nuget.org/packages/mosaik.core) - the Language enum will be one of them, and will do the fix then!

**Comment by theolivenbaum** [comment]
@matteofabbri just double checking, and it seems like wikipedia lists them both: https://en.wikipedia.org/wiki/Luxembourgish and https://en.wikipedia.org/wiki/Limburgish

If I'm not mistaken, the list of languages on the enum was auto-generated from this list: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by matteofabbri** [comment]
Cool, thanks. 
Talking about Mosaik.Core, i was trying to fix a couple of bug that causes deadlock in some enviroment like Microsoft Orleans, but the problem goes down inside the Mosaik.Core library and i dont find the code of that
