### ISSUE TITLE
Unified Verb Index Support? (and Roadmap?)

### ISSUE THREAD

**Issue by dgerding** [curiosity-ai/catalyst#35]
Hi,
Is there any chance there is already "[Unified Verb Index](http://verbs.colorado.edu/verb-index/)" support lurking or in the roadmap? If not, any chance it might make it into a roadmap or future release?

Thanks,
Dave G

**Comment by theolivenbaum** [comment]
Hi @dgerding, I'm not aware of what UVI stands for, could you elaborate how it's used?

**Comment by dgerding** [comment]
Hi @theolivenbaum.  It's the "Unified Verb Index" and seems to be the best verb alternative to Wordnet I could find. It brings coordinates VerbNet, PropBank, FrameNet and OntoNotes verb senses.

http://verbs.colorado.edu/verb-index/index.php
