### ISSUE TITLE
Sentence detection broken ? 

### ISSUE THREAD

**Issue by BernhardGlueck** [curiosity-ai/catalyst#41]
**Describe the bug**
Sentence detection only reacts to punctuation

**To Reproduce**
Use sentence detector on non punctuated sentences. ( not seperated ) 

**Expected behavior**
Sentence detector should detect when a sentence ends in the absence of punctuation

Also note when training Sentence detector models from scratch using UD ... the resulting models are extremely small.. 2kb for english or german ...

**Comment by theolivenbaum** [comment]
Hi @BernhardGlueck , do you have an example of a sentence that causes this issue?
