### ISSUE TITLE
Regex timeout exception on processing document text

### ISSUE THREAD

**Issue by v-echo** [curiosity-ai/catalyst#46]
**Describe the bug**
Processing a slightly larger document text throws a RegexTimeoutException. 

**To Reproduce**
Extract the text from the attached document. Run a process pipeline against the extracted text. 

**Expected behavior**
The text should be processed correctly and no exception should be thrown.

**Screenshots**
![err_regex](https://user-images.githubusercontent.com/6671776/105053944-c6ea9a00-5a71-11eb-8c39-62e53eff7a31.PNG)

**Additional context**
Document used as a source (extracted with Apache Tika) is attached.
Also linked is the extracted text.
[Cillian_Murphy.pdf](https://github.com/curiosity-ai/catalyst/files/5836754/Cillian_Murphy.pdf)
https://paste.ee/p/trAmx

Edit: the bug is not a showstopper. It seems that it's internally handled somewhere, but I still wonder if it's normal behavior.

**Comment by theolivenbaum** [comment]
Thanks for reporting it! The regex timeout is a failsafe against getting stuck in edge conditions. Never hit it before but great to have a way to reproduce it locally - I'll push tomorrow a fix for it (and check how to better handle it too)

**Comment by theolivenbaum** [comment]
@v-echo thanks for the data to reproduce it - was easy to narrow down to this [URL regex test](https://github.com/curiosity-ai/catalyst/blob/1959273d77f3726d475a6f295577ae7fa68d5ba9/Catalyst/src/Base/CharSpanExtensions.cs#L220). We already had a timeout there to avoid the catastrophic backtracking from the regex, but I added a new test now that I see what's causing it - and that should fix the exception being thrown in most cases.

**Comment by v-echo** [comment]
It's not a problem, glad to help.
