### ISSUE TITLE
Help with AveragePerceptronEntityRecognizer for Danish

### ISSUE THREAD

**Issue by jeppesc11** [curiosity-ai/catalyst#52]
Hi,

Maybe it's i'm just a noob, but i can't figure out to get/create a model-WikiNER-v000000.binz for Danish AveragePerceptronEntityRecognizer?

Can you be helpful with this? Thank you! :-)

**Comment by theolivenbaum** [comment]
Hi @jeppesc11,

As I just answered on #53 , the WikiNER model is only available for a subset of the languages.

If you want to train your own, the best start is trying to find a dataset training NER models for the language you need.

If it's a public data-set, happy to include in the training code and publish it to NuGet.
