### ISSUE TITLE
.NET standard 2.0 actually not supported

### ISSUE THREAD

**Issue by OdinOxin** [curiosity-ai/catalyst#54]
Readme claims supporting .NET standard 2.0.

Package Catalyst 1.0.16767 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Catalyst 1.0.16767 supports:
  - net5.0 (.NETCoreApp,Version=v5.0)
  - netcoreapp3.1 (.NETCoreApp,Version=v3.1)
  - netstandard2.1 (.NETStandard,Version=v2.1)

**Comment by OdinOxin** [comment]
Even with Catalyst 1.0.18054

**Comment by williware** [comment]
It appears to me that the Mosaik.Core Nuget Package shows a dependency on Microsoft.Extensions.Logging.Abstractions >= 5.0.0 . See the list below from [https://www.nuget.org/packages/Mosaik.Core/0.0.21635/](url)

.NETCoreApp 3.1
MessagePack (>= 2.3.75)
Microsoft.CSharp (>= 4.7.0)
Microsoft.Extensions.Logging.Abstractions (>= 5.0.0)
Newtonsoft.Json (>= 13.0.1)
Nito.AsyncEx (>= 5.1.0)
SharpZipLib.NETStandard (>= 1.0.7)
System.Memory (>= 4.5.4)
System.Numerics.Vectors (>= 4.5.0)
System.Text.Json (>= 5.0.2)

**Comment by zbarnett** [comment]
It appears this is still an issue.
