### ISSUE TITLE
Mosaik.Core has a dependency on .NET 5 Microsoft.Extensions.Logging fails in Azure Funcs

### ISSUE THREAD

**Issue by williware** [curiosity-ai/catalyst#65]
**Describe the bug**
Azure Functions running under .Net Core 3.1 applications utilizing Catalyst Nuget package are unable to load due the dependency Mosaik.Core has on ,net 5 Microsoft.Extensions.Logging. 

**To Reproduce**
build an Azure Func in VS 2019 with Core Tools Version: 3.0.3904 and Function Runtime Version: 3.3.1.0  and add the Catalyst Nuget Package. Reference Catalyst in the code. Try to debug the function in VS 2019. The runtime fails to start. The runtime fails with 
A host error has occurred during startup operation '7b34dd36-ae2b-4d81-8322-302f63c2cf02'.
[2021-11-04T03:01:37.263Z] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Expected behavior**
without a reference to .net 5 the code would load and run successfully_

**Additional context**
![image](https://user-images.githubusercontent.com/510778/140251396-2bceacd3-fd99-4eb8-9e21-c612ada97ba1.png)

**Comment by theolivenbaum** [comment]
Hi @williware, thanks for reporting it - it's quite annoying that microsoft is so behind with their own usage of .NET...
I've bumped back the version of Microsoft.Extensions.Logging.Abstractions to 2.1.1 on the Mosaik.Core package, you should expect a new version of Catalyst in a few hours with the updated package!

Let me know if it works!

**Comment by theolivenbaum** [comment]
@williware: Should be fixed with https://www.nuget.org/packages/Catalyst/1.0.23175, can you test it? Will close for now, feel free to reopen the issue if you hit anything!

**Comment by williware** [comment]
I will download and give it a try.

Thanks
