### ISSUE TITLE
System.IO.FileNotFoundException: 'Unable to find the specified file.'

### ISSUE THREAD

**Issue by xbaha** [curiosity-ai/catalyst#79]
Fast Text Language Detector models are not found and not downloaded, It throws the error

```
Catalyst.Models.English.Register();
Storage.Current = new DiskStorage("catalyst-models");
--> var fastTextLanguageDetector = await FastTextLanguageDetector.FromStoreAsync(Mosaik.Core.Language.Any, Mosaik.Core.Version.Latest, "");
```

It's not clear if I need to download the trained data or if it's automatically downloaded.

**Comment by adriankozakiewicz** [comment]
You need to istall Mosaik.Core. Unfortunetly authors did not mention that this is required for lib to work (currently).
Then ofc add "using Mosaik.Core;"

**Comment by acuencadev** [comment]
I added a reference to Mosaik.Core as advised by @adriankozakiewicz and this is failing. Is there any other fix for this?

I am using .Net 8 and the following Packages:

<PackageReference Include="Catalyst" Version="1.0.40904" />
<PackageReference Include="Catalyst.Models.English" Version="1.0.30952" />
<PackageReference Include="Catalyst.Models.French" Version="1.0.30952" />
<PackageReference Include="Catalyst.Models.Japanese" Version="1.0.30952" />
<PackageReference Include="Mosaik.Core" Version="0.0.43755" />
