### ISSUE TITLE
Catalyst.Spacy.Test - urllib3 needs openssl 1.1.1+

### ISSUE THREAD

**Issue by sven-n** [curiosity-ai/catalyst#95]
**Describe the bug**
Running the ```Catalyst.Spacy.Test``` returns the following error:
```Unhandled exception. Python.Runtime.PythonException: ImportError : urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.1.0j  20 Nov 2018. See: https://github.com/urllib3/urllib3/issues/2168```

**To Reproduce**
* Open the solution in Visual Studio 2022.
* Debug/Run the project ```Catalyst.Spacy.Test```

**Expected behavior**
The processed document should be appear as json in the console.

**Screenshots**
![grafik](https://github.com/curiosity-ai/catalyst/assets/5238610/a4801731-dacb-4cfe-ac5f-88d063109d68)

**Comment by hitendra1851** [comment]
Is there any update on this , I am facing the same issue.

**Comment by sidneyaraujomelo** [comment]
I'm also facing the same issue

**Comment by theolivenbaum** [comment]
Most probably due to the older [Python.Included](https://www.nuget.org/packages/Python.Included) package used in [Catalyst.Spacy](https://www.nuget.org/packages/Catalyst.Spacy), I've updated it in e2bb759 and will update the test project to the latest Catalyst.Spacy package as soon as it is published to NuGet.

**Comment by sidneyaraujomelo** [comment]
The issue has been fixed, however, I'm getting the following error: "Runtime.PythonDLL was not set or does not point to a supported Python runtime DLL". I have tried setting Runtime.PythonDLL to the python37.dll installed by Python.Installer but it didn't work. Should I create another issue?
